# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/internal/self_recursive.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/protobuf/internal/self_recursive.proto',
  package='google.protobuf.python.internal',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n-google/protobuf/internal/self_recursive.proto\x12\x1fgoogle.protobuf.python.internal\"\xd5\x01\n\rSelfRecursive\x12U\n\x0erecursivegroup\x18\x01 \x01(\n2=.google.protobuf.python.internal.SelfRecursive.RecursiveGroup\x1am\n\x0eRecursiveGroup\x12P\n\tsub_group\x18\x02 \x01(\x0b\x32=.google.protobuf.python.internal.SelfRecursive.RecursiveGroup\x12\t\n\x01i\x18\x03 \x01(\x05'
)




_SELFRECURSIVE_RECURSIVEGROUP = _descriptor.Descriptor(
  name='RecursiveGroup',
  full_name='google.protobuf.python.internal.SelfRecursive.RecursiveGroup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sub_group', full_name='google.protobuf.python.internal.SelfRecursive.RecursiveGroup.sub_group', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='i', full_name='google.protobuf.python.internal.SelfRecursive.RecursiveGroup.i', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=296,
)

_SELFRECURSIVE = _descriptor.Descriptor(
  name='SelfRecursive',
  full_name='google.protobuf.python.internal.SelfRecursive',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='recursivegroup', full_name='google.protobuf.python.internal.SelfRecursive.recursivegroup', index=0,
      number=1, type=10, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SELFRECURSIVE_RECURSIVEGROUP, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=296,
)

_SELFRECURSIVE_RECURSIVEGROUP.fields_by_name['sub_group'].message_type = _SELFRECURSIVE_RECURSIVEGROUP
_SELFRECURSIVE_RECURSIVEGROUP.containing_type = _SELFRECURSIVE
_SELFRECURSIVE.fields_by_name['recursivegroup'].message_type = _SELFRECURSIVE_RECURSIVEGROUP
DESCRIPTOR.message_types_by_name['SelfRecursive'] = _SELFRECURSIVE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SelfRecursive = _reflection.GeneratedProtocolMessageType('SelfRecursive', (_message.Message,), {

  'RecursiveGroup' : _reflection.GeneratedProtocolMessageType('RecursiveGroup', (_message.Message,), {
    'DESCRIPTOR' : _SELFRECURSIVE_RECURSIVEGROUP,
    '__module__' : 'google.protobuf.internal.self_recursive_pb2'
    # @@protoc_insertion_point(class_scope:google.protobuf.python.internal.SelfRecursive.RecursiveGroup)
    })
  ,
  'DESCRIPTOR' : _SELFRECURSIVE,
  '__module__' : 'google.protobuf.internal.self_recursive_pb2'
  # @@protoc_insertion_point(class_scope:google.protobuf.python.internal.SelfRecursive)
  })
_sym_db.RegisterMessage(SelfRecursive)
_sym_db.RegisterMessage(SelfRecursive.RecursiveGroup)


# @@protoc_insertion_point(module_scope)
